test: test


create_faiss: false
create_embedding: false

embedded_type: 
  store: AzureOpenAIEmbeddings
  retrieve: AzureOpenAIEmbeddings

store:
  embedded_path: data/processed/embedded
  faiss_index_path: data/processed/faiss_index
  extractor_type: extracted # select -> [extracted:抽出済みのドキュメントを使用, custom: 独自の抽出機構, azure: Azure Documentの抽出機構]
  chunk_size: 2000
  chunk_overlap: 200
  merge_image_text: True # 画像説明テキストを抽出されたマークダウンと同じチャンクとして結合させるか
  text_extractor_type: pdfplumber
  paipline_config:
    include_tables: true
    linearize_tables: False
    summarize_tables: true
    caption_images: False
    store_image_captions: False

retrieve:
  search:
    top_k: 8
    fetch_k: 40
    return_text: True

augmentprompt:
  system_content_path: prompts_management/system_content/1.txt
  user_content_path: prompts_management/user_content/o1-preview.txt
  mode: concise

generate:
  model: o1-preview
  max_tokens: 54
  temperature: 0.7