test: test


create_faiss: false
create_embedding: false

embedded_type: 
  store: AzureOpenAIEmbeddings
  retrieve: AzureOpenAIEmbeddings

store:
  embedded_path: data/processed/embedded
  faiss_index_path: data/processed/faiss_index
  chunk_size: 2000
  chunk_overlap: 200

retrieve:
  search:
    top_k: 5
    fetch_k: 20
    return_text: True

augmentprompt:
  system_content_path: prompts_management/system_content/1.txt
  user_content_path: prompts_management/user_content/1.txt
  mode: concise

generate:
  model: 4omini
  max_tokens: 54
  temperature: 0.7